[tool.poetry]
name = "premise"
version = "0.1.0"
description = ""
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
tqdm = "^4.67.0"
stormpy = { path = "../stormpy-premise"}
black = "^24.10.0"
py-spy = "^0.4.0"
scenic = "^3.0.0"
jupyter = "^1.1.1"
scikit-learn = "^1.6.1"
torch = "^2.7.0"
torchvision = "^0.22.0"
carla = "^0.9.15"

[tool.poetry.group.dev.dependencies]
pybind11-stubgen = "^2.5.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
