[tool.poetry]
name = "premise"
version = "0.1.0"
description = ""
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
stormpy = { path = "../stormpy-premise", develop = true }
tqdm = "^4.67.0"
numpy = "^2.1.3"
black = "^24.10.0"
py-spy = "^0.4.0"

[tool.poetry.group.dev.dependencies]
pybind11-stubgen = "^2.5.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
