# python -u -m premise.interval.run 12h stats_path -sv x -mc grid-line-5 --run-id=run_id -t --dump-stats out/stats/date/grid-line-5-coarse_refinement-stats-run_id.npy -v -m out/models/date/grid-line-5-coarse_refinement-run_id :: -sv x -mc grid-line-5 --run-id=run_id -m out/models/date/grid-line-5-coarse-comp-reg-run_id --dump-stats out/stats/date/grid-line-5-coarse-comp-reg-stats-run_id.npy :: -sv x -mc grid-line-5 --run-id=run_id -m out/models/date/grid-line-5-coarse-comp-mle-run_id --dump-stats out/stats/date/grid-line-5-coarse-comp-mle-stats-run_id.npy
# python -u -m premise.interval.run 12h stats_path -sv x -mc grid-line-20 --run-id=run_id -t --dump-stats out/stats/date/grid-line-20-coarse_refinement-stats-run_id.npy -v -m out/models/date/grid-line-20-coarse_refinement-run_id :: -sv x -mc grid-line-20 --run-id=run_id -m out/models/date/grid-line-20-coarse-comp-reg-run_id --dump-stats out/stats/date/grid-line-20-coarse-comp-reg-stats-run_id.npy :: -sv x -mc grid-line-20 --run-id=run_id -m out/models/date/grid-line-20-coarse-comp-mle-run_id --dump-stats out/stats/date/grid-line-20-coarse-comp-mle-stats-run_id.npy

# python -u -m premise.interval.run 12h stats_path -sv x -mc grid-walls-5 --run-id=run_id -t --dump-stats out/stats/date/grid-walls-5-coarse_refinement-stats-run_id.npy -v -m out/models/date/grid-walls-5-coarse_refinement-run_id :: -sv x -mc grid-walls-5 --run-id=run_id -m out/models/date/grid-walls-5-coarse-comp-reg-run_id --dump-stats out/stats/date/grid-walls-5-coarse-comp-reg-stats-run_id.npy :: -sv x -mc grid-walls-5 --run-id=run_id -m out/models/date/grid-walls-5-coarse-comp-mle-run_id --dump-stats out/stats/date/grid-walls-5-coarse-comp-mle-stats-run_id.npy
# python -u -m premise.interval.run 12h stats_path -sv x -mc grid-walls-20 --run-id=run_id -t --dump-stats out/stats/date/grid-walls-20-coarse_refinement-stats-run_id.npy -v -m out/models/date/grid-walls-20-coarse_ref-run_id :: -sv x -mc grid-walls-20 --run-id=run_id -m out/models/date/grid-walls-20-coarse-comp-reg-run_id --dump-stats out/stats/date/grid-walls-20-coarse-comp-reg-stats-run_id.npy :: -sv x -mc grid-walls-20 --run-id=run_id -m out/models/date/grid-walls-20-coarse-comp-mle-run_id --dump-stats out/stats/date/grid-walls-20-coarse-comp-mle-stats-run_id.npy

# python -u -m premise.interval.run 12h stats_path -mc unlikely-15 -sp 5 --run-id=run_id -t --dump-stats out/stats/date/unlikely-15-comp-ref-stats-run_id.npy -v -m out/models/date/unlikely-15-comp-ref-run_id :: -mc unlikely-15 --run-id=run_id -m out/models/date/unlikely-15-comp-reg-run_id --dump-stats out/stats/date/unlikely-15-comp-reg-stats-run_id.npy :: -mc unlikely-15 --run-id=run_id -m out/models/date/unlikely-15-comp-mle-run_id --dump-stats out/stats/date/unlikely-15-comp-mle-stats-run_id.npy
#python -u -m premise.interval.run 12h stats_path -mc all-rare-2 -sp 5 --run-id=run_id -t --dump-stats out/stats/date/all-rare-2-comp-ref-stats-run_id.npy -v -m out/models/date/all-rare-2-comp-ref-run_id :: -mc all-rare-2 --run-id=run_id -m out/models/date/all-rare-2-comp-reg-run_id --dump-stats out/stats/date/all-rare-2-comp-reg-stats-run_id.npy :: -mc all-rare-2 --run-id=run_id -m out/models/date/all-rare-2-comp-mle-run_id --dump-stats out/stats/date/all-rare-2-comp-mle-stats-run_id.npy

python -u -m premise.interval.run 12h stats_path -mc antonina -sp 3 --run-id=run_id -t --dump-stats out/stats/date/antonina-comp-ref-stats-run_id.npy -v -m out/models/date/antonina-comp-ref-run_id :: -mc antonina --run-id=run_id -m out/models/date/antonina-comp-reg-run_id --dump-stats out/stats/date/antonina-comp-reg-stats-run_id.npy :: -mc antonina --run-id=run_id -m out/models/date/antonina-comp-mle-run_id --dump-stats out/stats/date/antonina-comp-mle-stats-run_id.npy


